### ISSUE TITLE
Roll Ball : Make the Canvas Responsive

### ISSUE THREAD

**Issue by n-ce** [n-ce/Bromage#10]
Currently its not properly displaying on devices with less width, make the canvas responsive so as it fits all screens.

**Comment by bhimeshagrawal** [comment]
Hey @n-ce Can i work on this issue ? Please assign me

**Comment by n-ce** [comment]
> Hey @n-ce Can i work on this issue ? Please assign me

Yes. Go for it!

**Comment by bhimeshagrawal** [comment]
Hey @n-ce , Can you add the hacktoberfest-accepted label to this issue
