### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by n-ce** [n-ce/Bromage#11]
Improve readme so as to highlight what this project best stands for, the potential of it and with proper screenshots, badges and icons.

**Comment by JanviRaina** [comment]
I can add some screenshots and badges. Will that do?

**Comment by n-ce** [comment]
> I can add some screenshots and badges. Will that do?

Sure, thanks

**Comment by JanviRaina** [comment]
I had a doubt. 
Here you have mentioned hactoberfest in labels, so I had added the hacktoberfest badge in the readme but in my Hacktoberfest contributions page, for this project it shows "Project not participating".

And for the website, I noticed that for the sine wave Audio generator, after it is turned on, even if we click on 'Back' button, still the audio keeps on playing in the background.

**Comment by n-ce** [comment]
I am not sure about the hacktoberfest label as another Dev suggested me to add it so i did.
You found that bug 😪 maybe I'll finally look for a solution like trigger stop event when back is clicked.
(well just fixed in theory https://github.com/n-ce/Bromage/commit/9da69f6719d13b63789a4c7245c5c815a145e229)

**Comment by JanviRaina** [comment]
I guess, you haven't registered for Hacktoberfest, that's why the PRs don't add as contributions maybe.
